### ISSUE TITLE
inawork

### ISSUE THREAD

**Issue by kimitaWanjohi** [Ibrah-55/mpesa-api-and-stk-push-Intergration#1]

**Comment by Ibrah-55** [comment]
Yeah roughly

**Comment by kimitaWanjohi** [comment]
na webhook umehandle

**Comment by Ibrah-55** [comment]
Yeah  it sends the http request then a message success

**Comment by kimitaWanjohi** [comment]
after the transaction is done, they send something like this to the callback_url specified in the request.
{
    "Body": {
        "stkCallback": {
            "MerchantRequestID": "50233-54363876-1",
            "CheckoutRequestID": "ws_CO_19052022131221388792177975",
            "ResultCode": 0,
            "ResultDesc": "The service request is processed successfully.",
            "CallbackMetadata": {
                "Item": [
                    {
                        "Name": "Amount",
                        "Value": 1
                    },
                    {
                        "Name": "MpesaReceiptNumber",
                        "Value": "QEJ59FNF6H"
                    },
                    {
                        "Name": "TransactionDate",
                        "Value": 20220519131303
                    },
                    {
                        "Name": "PhoneNumber",
                        "Value": 254792177975
                    }
                ]
            }
        }
    }
}

**Comment by Ibrah-55** [comment]
No. Just sends the message success. I was planning the callback url using
postman

**Comment by Jace254** [comment]
I have a question unrelated to this topic>>
Is it possible, by using the MPesa API , to authenticate user phone numbers with the hakikisha functionality...Thinking of it in a production setting where you have to authenticate multiple users

**Comment by Ibrah-55** [comment]
Using lipa na mpesa follows the usual transaction process so the user can do the hakikisha on their side

**Comment by Jace254** [comment]
What I'm trying to do is make an authentication api that tests whether the number the user has used to register in my app is a valid mpesa number or not..Only that, without having to initiate transactions.
So is there an existing endpoint for this or is it something you have to enquire with saf directly

**Comment by Jace254** [comment]
> No. Just sends the message success. I was planning the callback url using postman
> […](#)


Consider using cypress it's much more convinient and supplements usability and functionality tests done by postman

**Comment by kimitaWanjohi** [comment]
> What I'm trying to do is make an authentication api that tests whether the number the user has used to register in my app is a valid mpesa number or not..Only that, without having to initiate transactions. So is there an existing endpoint for this or is it something you have to enquire with saf directly

I don't think there is

**Comment by kimitaWanjohi** [comment]
> > No. Just sends the message success. I was planning the callback url using postman
> > […](#)
> 
> Consider using cypress it's much more convinient and supplements usability and functionality tests done by postman

I'll concider it

**Comment by Ibrah-55** [comment]
> What I'm trying to do is make an authentication api that tests whether the number the user has used to register in my app is a valid mpesa number or not..Only that, without having to initiate transactions. So is there an existing endpoint for this or is it something you have to enquire with saf directly

What you'd probably do is try checking if the phone number given is a valid safaricom number.

**Comment by Ibrah-55** [comment]
> > No. Just sends the message success. I was planning the callback url using postman
> > […](#)
> 
> Consider using cypress it's much more convinient and supplements usability and functionality tests done by postman

Alright
